<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::insert(" INSERT INTO `cities` (`gov_id`, `name_ar`, `name_en`) VALUES
( 1, 'القاهره', 'Cairo'),
( 2, 'الجيزة', 'Giza'),
( 2, 'السادس من أكتوبر', 'Sixth of October'),
( 2, 'الشيخ زايد\n', 'Cheikh Zayed'),
( 2, 'الحوامدية', 'Hawamdiyah'),
( 2, 'البدرشين', 'Al Badrasheen'),
( 2, 'الصف', 'Saf'),
( 2, 'أطفيح', 'Atfih'),
( 2, 'العياط', 'Al Ayat'),
( 2, 'الباويطي', 'Al-Bawaiti'),
( 2, 'منشأة القناطر', 'ManshiyetAl Qanater'),
( 2, 'أوسيم', 'Oaseem'),
( 2, 'كرداسة', 'Kerdasa'),
( 2, 'أبو النمرس', 'Abu Nomros'),
( 2, 'كفر غطاطي', 'Kafr Ghati'),
( 2, 'منشأة البكاري', 'Manshiyet Al Bakari'),
( 3, 'الأسكندرية', 'Alexandria'),
( 3, 'برج العرب', 'Burj Al Arab'),
( 3, 'برج العرب الجديدة', 'New Burj Al Arab'),
( 12, 'بنها', 'Banha'),
( 12, 'قليوب', 'Qalyub'),
( 12, 'شبرا الخيمة', 'Shubra Al Khaimah'),
( 12, 'القناطر الخيرية', 'Al Qanater Charity'),
( 12, 'الخانكة', 'Khanka'),
( 12, 'كفر شكر', 'Kafr Shukr'),
( 12, 'طوخ', 'Tukh'),
( 12, 'قها', 'Qaha'),
( 12, 'العبور', 'Obour'),
( 12, 'الخصوص', 'Khosous'),
( 12, 'شبين القناطر', 'Shibin Al Qanater'),
( 6, 'دمنهور', 'Damanhour'),
( 6, 'كفر الدوار', 'Kafr El Dawar'),
( 6, 'رشيد', 'Rashid'),
( 6, 'إدكو', 'Edco'),
( 6, 'أبو المطامير', 'Abu al-Matamir'),
( 6, 'أبو حمص', 'Abu Homs'),
( 6, 'الدلنجات', 'Delengat'),
( 6, 'المحمودية', 'Mahmoudiyah'),
( 6, 'الرحمانية', 'Rahmaniyah'),
( 6, 'إيتاي البارود', 'Itai Baroud'),
( 6, 'حوش عيسى', 'Housh Eissa'),
( 6, 'شبراخيت', 'Shubrakhit'),
( 6, 'كوم حمادة', 'Kom Hamada'),
( 6, 'بدر', 'Badr'),
( 6, 'وادي النطرون', 'Wadi Natrun'),
( 6, 'النوبارية الجديدة', 'New Nubaria'),
( 23, 'مرسى مطروح', 'Marsa Matrouh'),
( 23, 'الحمام', 'El Hamam'),
( 23, 'العلمين', 'Alamein'),
( 23, 'الضبعة', 'Dabaa'),
( 23, 'النجيلة', 'Al-Nagila'),
( 23, 'سيدي براني', 'Sidi Brani'),
( 23, 'السلوم', 'Salloum'),
( 23, 'سيوة', 'Siwa'),
( 19, 'دمياط', 'Damietta'),
( 19, 'دمياط الجديدة', 'New Damietta'),
( 19, 'رأس البر', 'Ras El Bar'),
( 19, 'فارسكور', 'Faraskour'),
( 19, 'الزرقا', 'Zarqa'),
( 19, 'السرو', 'alsaru'),
( 19, 'الروضة', 'alruwda'),
( 19, 'كفر البطيخ', 'Kafr El-Batikh'),
( 19, 'عزبة البرج', 'Azbet Al Burg'),
( 19, 'ميت أبو غالب', 'Meet Abou Ghalib'),
( 19, 'كفر سعد', 'Kafr Saad'),
( 4, 'المنصورة', 'Mansoura'),
( 4, 'طلخا', 'Talkha'),
( 4, 'ميت غمر', 'Mitt Ghamr'),
( 4, 'دكرنس', 'Dekernes'),
( 4, 'أجا', 'Aga'),
( 4, 'منية النصر', 'Menia El Nasr'),
( 4, 'السنبلاوين', 'Sinbillawin'),
( 4, 'الكردي', 'El Kurdi'),
( 4, 'بني عبيد', 'Bani Ubaid'),
( 4, 'المنزلة', 'Al Manzala'),
( 4, 'تمي الأمديد', 'tami al\'amdid'),
( 4, 'الجمالية', 'aljamalia'),
( 4, 'شربين', 'Sherbin'),
( 4, 'المطرية', 'Mataria'),
( 4, 'بلقاس', 'Belqas'),
( 4, 'ميت سلسيل', 'Meet Salsil'),
( 4, 'جمصة', 'Gamasa'),
( 4, 'محلة دمنة', 'Mahalat Damana'),
( 4, 'نبروه', 'Nabroh'),
( 22, 'كفر الشيخ', 'Kafr El Sheikh'),
( 22, 'دسوق', 'Desouq'),
( 22, 'فوه', 'Fooh'),
( 22, 'مطوبس', 'Metobas'),
( 22, 'برج البرلس', 'Burg Al Burullus'),
( 22, 'بلطيم', 'Baltim'),
( 22, 'مصيف بلطيم', 'Masief Baltim'),
( 22, 'الحامول', 'Hamol'),
( 22, 'بيلا', 'Bella'),
( 22, 'الرياض', 'Riyadh'),
( 22, 'سيدي سالم', 'Sidi Salm'),
( 22, 'قلين', 'Qellen'),
( 22, 'سيدي غازي', 'Sidi Ghazi'),
( 8, 'طنطا', 'Tanta'),
( 8, 'المحلة الكبرى', 'Al Mahalla Al Kobra'),
( 8, 'كفر الزيات', 'Kafr El Zayat'),
( 8, 'زفتى', 'Zefta'),
( 8, 'السنطة', 'El Santa'),
( 8, 'قطور', 'Qutour'),
( 8, 'بسيون', 'Basion'),
( 8, 'سمنود', 'Samannoud'),
( 10, 'شبين الكوم', 'Shbeen El Koom'),
( 10, 'مدينة السادات', 'Sadat City'),
( 10, 'منوف', 'Menouf'),
( 10, 'سرس الليان', 'Sars El-Layan'),
( 10, 'أشمون', 'Ashmon'),
( 10, 'الباجور', 'Al Bagor'),
( 10, 'قويسنا', 'Quesna'),
( 10, 'بركة السبع', 'Berkat El Saba'),
( 10, 'تلا', 'Tala'),
( 10, 'الشهداء', 'Al Shohada'),
( 20, 'الزقازيق', 'Zagazig'),
( 20, 'العاشر من رمضان', 'Al Ashr Men Ramadan'),
( 20, 'منيا القمح', 'Minya Al Qamh'),
( 20, 'بلبيس', 'Belbeis'),
( 20, 'مشتول السوق', 'Mashtoul El Souq'),
( 20, 'القنايات', 'Qenaiat'),
( 20, 'أبو حماد', 'Abu Hammad'),
( 20, 'القرين', 'El Qurain'),
( 20, 'ههيا', 'Hehia'),
( 20, 'أبو كبير', 'Abu Kabir'),
( 20, 'فاقوس', 'Faccus'),
( 20, 'الصالحية الجديدة', 'El Salihia El Gedida'),
( 20, 'الإبراهيمية', 'Al Ibrahimiyah'),
( 20, 'ديرب نجم', 'Deirb Negm'),
( 20, 'كفر صقر', 'Kafr Saqr'),
( 20, 'أولاد صقر', 'Awlad Saqr'),
( 20, 'الحسينية', 'Husseiniya'),
( 20, 'صان الحجر القبلية', 'san alhajar alqablia'),
( 20, 'منشأة أبو عمر', 'Manshayat Abu Omar'),
( 18, 'بورسعيد', 'PorSaid'),
( 18, 'بورفؤاد', 'PorFouad'),
( 9, 'الإسماعيلية', 'Ismailia'),
( 9, 'فايد', 'Fayed'),
( 9, 'القنطرة شرق', 'Qantara Sharq'),
( 9, 'القنطرة غرب', 'Qantara Gharb'),
( 9, 'التل الكبير', 'El Tal El Kabier'),
( 9, 'أبو صوير', 'Abu Sawir'),
( 9, 'القصاصين الجديدة', 'Kasasien El Gedida'),
( 14, 'السويس', 'Suez'),
( 26, 'العريش', 'Arish'),
( 26, 'الشيخ زويد', 'Sheikh Zowaid'),
( 26, 'نخل', 'Nakhl'),
( 26, 'رفح', 'Rafah'),
( 26, 'بئر العبد', 'Bir al-Abed'),
( 26, 'الحسنة', 'Al Hasana'),
( 21, 'الطور', 'Al Toor'),
( 21, 'شرم الشيخ', 'Sharm El-Shaikh'),
( 21, 'دهب', 'Dahab'),
( 21, 'نويبع', 'Nuweiba'),
( 21, 'طابا', 'Taba'),
( 21, 'سانت كاترين', 'Saint Catherine'),
( 21, 'أبو رديس', 'Abu Redis'),
( 21, 'أبو زنيمة', 'Abu Zenaima'),
( 21, 'رأس سدر', 'Ras Sidr'),
( 17, 'بني سويف', 'Bani Sweif'),
( 17, 'بني سويف الجديدة', 'Beni Suef El Gedida'),
( 17, 'الواسطى', 'Al Wasta'),
( 17, 'ناصر', 'Naser'),
( 17, 'إهناسيا', 'Ehnasia'),
( 17, 'ببا', 'beba'),
( 17, 'الفشن', 'Fashn'),
( 17, 'سمسطا', 'Somasta'),
( 7, 'الفيوم', 'Fayoum'),
( 7, 'الفيوم الجديدة', 'Fayoum El Gedida'),
( 7, 'طامية', 'Tamiya'),
( 7, 'سنورس', 'Snores'),
( 7, 'إطسا', 'Etsa'),
( 7, 'إبشواي', 'Epschway'),
( 7, 'يوسف الصديق', 'Yusuf El Sediaq'),
( 11, 'المنيا', 'Minya'),
( 11, 'المنيا الجديدة', 'Minya El Gedida'),
( 11, 'العدوة', 'El Adwa'),
( 11, 'مغاغة', 'Magagha'),
( 11, 'بني مزار', 'Bani Mazar'),
( 11, 'مطاي', 'Mattay'),
( 11, 'سمالوط', 'Samalut'),
( 11, 'المدينة الفكرية', 'Madinat El Fekria'),
( 11, 'ملوي', 'Meloy'),
( 11, 'دير مواس', 'Deir Mawas'),
( 16, 'أسيوط', 'Assiut'),
( 16, 'أسيوط الجديدة', 'Assiut El Gedida'),
( 16, 'ديروط', 'Dayrout'),
( 16, 'منفلوط', 'Manfalut'),
( 16, 'القوصية', 'Qusiya'),
( 16, 'أبنوب', 'Abnoub'),
( 16, 'أبو تيج', 'Abu Tig'),
( 16, 'الغنايم', 'El Ghanaim'),
( 16, 'ساحل سليم', 'Sahel Selim'),
( 16, 'البداري', 'El Badari'),
( 16, 'صدفا', 'Sidfa'),
( 13, 'الخارجة', 'El Kharga'),
( 13, 'باريس', 'Paris'),
( 13, 'موط', 'Mout'),
( 13, 'الفرافرة', 'Farafra'),
( 13, 'بلاط', 'Balat'),
( 5, 'الغردقة', 'Hurghada'),
( 5, 'رأس غارب', 'Ras Ghareb'),
( 5, 'سفاجا', 'Safaga'),
( 5, 'القصير', 'El Qusiar'),
( 5, 'مرسى علم', 'Marsa Alam'),
( 5, 'الشلاتين', 'Shalatin'),
( 5, 'حلايب', 'Halaib'),
( 27, 'سوهاج', 'Sohag'),
( 27, 'سوهاج الجديدة', 'Sohag El Gedida'),
( 27, 'أخميم', 'Akhmeem'),
( 27, 'أخميم الجديدة', 'Akhmim El Gedida'),
( 27, 'البلينا', 'Albalina'),
( 27, 'المراغة', 'El Maragha'),
( 27, 'المنشأة', 'almunsha\'a'),
( 27, 'دار السلام', 'Dar AISalaam'),
( 27, 'جرجا', 'Gerga'),
( 27, 'جهينة الغربية', 'Jahina Al Gharbia'),
( 27, 'ساقلته', 'Saqilatuh'),
( 27, 'طما', 'Tama'),
( 27, 'طهطا', 'Tahta'),
( 25, 'قنا', 'Qena'),
( 25, 'قنا الجديدة', 'New Qena'),
( 25, 'أبو تشت', 'Abu Tesht'),
( 25, 'نجع حمادي', 'Nag Hammadi'),
( 25, 'دشنا', 'Deshna'),
( 25, 'الوقف', 'Alwaqf'),
( 25, 'قفط', 'Qaft'),
( 25, 'نقادة', 'Naqada'),
( 25, 'فرشوط', 'Farshout'),
( 25, 'قوص', 'Quos'),
( 24, 'الأقصر', 'Luxor'),
( 24, 'الأقصر الجديدة', 'New Luxor'),
( 24, 'إسنا', 'Esna'),
( 24, 'طيبة الجديدة', 'New Tiba'),
( 24, 'الزينية', 'Al ziynia'),
( 24, 'البياضية', 'Al Bayadieh'),
( 24, 'القرنة', 'Al Qarna'),
( 24, 'أرمنت', 'Armant'),
( 24, 'الطود', 'Al Tud'),
( 15, 'أسوان', 'Aswan'),
( 15, 'أسوان الجديدة', 'Aswan El Gedida'),
( 15, 'دراو', 'Drau'),
( 15, 'كوم أمبو', 'Kom Ombo'),
( 15, 'نصر النوبة', 'Nasr Al Nuba'),
( 15, 'كلابشة', 'Kalabsha'),
( 15, 'إدفو', 'Edfu'),
( 15, 'الرديسية', 'Al-Radisiyah'),
( 15, 'البصيلية', 'Al Basilia'),
( 15, 'السباعية', 'Al Sibaeia'),
( 15, 'ابوسمبل السياحية', 'Abo Simbl Al Siyahia')");
    }
}
